### ISSUE TITLE
JSON error while posting since 6/3/2024 to framapiaf.org

### ISSUE THREAD

**Issue by ArfyFR** [valerio-vaccaro/node-red-contrib-mastodon#8]
Hi,
framapiaf.org is a Mastodon where I post my blogs (RSS to Mastodon)

7 Mar 06:50:36 - [info] Node-RED version: v3.1.6
7 Mar 06:50:36 - [info] Node.js  version: v20.9.0
7 Mar 06:50:36 - [info] Windows_NT 10.0.22631 x64 LE

node-red-contrib-mastodon: 0.1.1

Since yesterday, when my bot tries to sendMessage to my Mastodon, I face this:
```
Error: JSON decode error: Mastodon HTTP response body was not valid JSON
    at exports.makeMastodonError (<PATH>\.node-red\node_modules\mastodon\lib\helpers.js:57:13)
    at onRequestComplete (<PATH>\.node-red\node_modules\mastodon\lib\mastodon.js:215:27)
    at Request.<anonymous> (<PATH>\.node-red\node_modules\mastodon\lib\mastodon.js:246:7)
    at Request.emit (node:events:526:35)
    at IncomingMessage.<anonymous> (<PATH>\.node-red\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: null,
  allErrors: [],
  mastodonReply: null,
  statusCode: 500
}
```

And in Mastodon: all looks well:
![image](https://github.com/valerio-vaccaro/node-red-contrib-mastodon/assets/3436322/d26a5e6a-86ae-4375-8ed8-fe7648e96e6c)

A suggestion of what I can do / ask ?

I asked to framapiaf, but didn't a reply yet: https://framapiaf.org/@Arfy/112049223318777240

**Comment by ArfyFR** [comment]
Hmm, this morning after opening the node sendMessage I noticed "something was modified" and node-red asked to save my nodes
It seems to work again, I'll check for next posts from RSS

**Comment by ArfyFR** [comment]
Closing, it's working well after "saving" nodes (without modifying something)
